name = "cf-auth-flag-worker"
main = "src/index.js"
compatibility_date = "2025-08-13"
workers_dev = false
account_id = ""

[env.production]
zone_id = ""

[[env.production.routes]]
pattern = "myinstance.bournemd.com/secure*"

[[env.production.r2_buckets]]
binding = "FLAGS_BUCKET"
bucket_name = "country-flags"
preview_bucket_name = "country-flags"

